import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import siteMetadata from '@/data/siteMetadata'
import Header from './components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang={siteMetadata.language}>
      <body className="bg-white text-black antialiased dark:bg-gray-950 dark:text-white">
        <Header />
        <main className="mb-auto">{children}</main>
      </body>
    </html>
  )
}
